### ISSUE TITLE
/MeshNetSimulator-amd64-linux  ..how to build this one?

### ISSUE THREAD

**Issue by DLinIoTedge** [mwarning/MeshNetSimulator#8]
How to build  MeshNetSimulator-

**Comment by mwarning** [comment]
hi,

I just call `cargo build` in the repository folder (or `cargo run`). Cargo is the build tool used for Rust projects.

Anyway, the project needs Rust knowledge to actually make use of it. So I far I mostly use it to tinker with algorithms and do quick and dirty programming. It might be of no use to you.

But [this project](https://github.com/mwarning/meshnet-lab) is actually working out of the box.

**Comment by mwarning** [comment]
I have added a sentence on how to build the program: https://github.com/mwarning/MeshNetSimulator/commit/d4d6e7241025c96dff947980caef3a3e88062627

I hope this will help.
